language: python
python:
  - "3.5"

# command to install dependencies
install:
- pip install coverage python-coveralls 'pyparser==0.0.3' 'grammpy==1.2.1'

# command to run tests with coverage
script:
- coverage run --source=grammpy_transforms -m unittest discover -s tests -p "*Test.py" -q

# report coverage
after_script:
- coverage report -m
- coveralls

# disable email notifications
notifications:
  email: false
